# coding: utf-8

"""
    AddSkill

    This is the swagger for LockDownMainHealthy at AddSkill.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: akanksha@addskill.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class MealApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def add_meal(self, body, **kwargs):  # noqa: E501
        """Add meal  # noqa: E501

        This can only be done by the logged in user.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.add_meal(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Meal body: Meal object to Add (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.add_meal_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.add_meal_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def add_meal_with_http_info(self, body, **kwargs):  # noqa: E501
        """Add meal  # noqa: E501

        This can only be done by the logged in user.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.add_meal_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Meal body: Meal object to Add (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method add_meal" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `add_meal`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/xml', 'application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/meals', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_meal(self, meal_id, **kwargs):  # noqa: E501
        """Delete meal entry  # noqa: E501

        This can only be done by the logged in user.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_meal(meal_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str meal_id: The meal that needs to be deleted. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_meal_with_http_info(meal_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_meal_with_http_info(meal_id, **kwargs)  # noqa: E501
            return data

    def delete_meal_with_http_info(self, meal_id, **kwargs):  # noqa: E501
        """Delete meal entry  # noqa: E501

        This can only be done by the logged in user.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_meal_with_http_info(meal_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str meal_id: The meal that needs to be deleted. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['meal_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_meal" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'meal_id' is set
        if ('meal_id' not in params or
                params['meal_id'] is None):
            raise ValueError("Missing the required parameter `meal_id` when calling `delete_meal`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'meal_id' in params:
            path_params['meal_id'] = params['meal_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/xml', 'application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/meals/{meal_id}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_meal_by_meal_id(self, meal_id, **kwargs):  # noqa: E501
        """Get meal by meal id  # noqa: E501

        Get Meal by specifying the meal ID  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_meal_by_meal_id(meal_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str meal_id: The meal that needs to be fetched. (required)
        :return: Meal
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_meal_by_meal_id_with_http_info(meal_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_meal_by_meal_id_with_http_info(meal_id, **kwargs)  # noqa: E501
            return data

    def get_meal_by_meal_id_with_http_info(self, meal_id, **kwargs):  # noqa: E501
        """Get meal by meal id  # noqa: E501

        Get Meal by specifying the meal ID  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_meal_by_meal_id_with_http_info(meal_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str meal_id: The meal that needs to be fetched. (required)
        :return: Meal
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['meal_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_meal_by_meal_id" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'meal_id' is set
        if ('meal_id' not in params or
                params['meal_id'] is None):
            raise ValueError("Missing the required parameter `meal_id` when calling `get_meal_by_meal_id`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'meal_id' in params:
            path_params['meal_id'] = params['meal_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/xml', 'application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/meals/{meal_id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Meal',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def update_meal(self, meal_id, body, **kwargs):  # noqa: E501
        """Update Meal entry  # noqa: E501

        This can only be done by the logged in user.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_meal(meal_id, body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str meal_id: meal that needs to be updated (required)
        :param Meal body: Updated meal object (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.update_meal_with_http_info(meal_id, body, **kwargs)  # noqa: E501
        else:
            (data) = self.update_meal_with_http_info(meal_id, body, **kwargs)  # noqa: E501
            return data

    def update_meal_with_http_info(self, meal_id, body, **kwargs):  # noqa: E501
        """Update Meal entry  # noqa: E501

        This can only be done by the logged in user.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_meal_with_http_info(meal_id, body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str meal_id: meal that needs to be updated (required)
        :param Meal body: Updated meal object (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['meal_id', 'body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_meal" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'meal_id' is set
        if ('meal_id' not in params or
                params['meal_id'] is None):
            raise ValueError("Missing the required parameter `meal_id` when calling `update_meal`")  # noqa: E501
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `update_meal`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'meal_id' in params:
            path_params['meal_id'] = params['meal_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/xml', 'application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/meals/{meal_id}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
