# coding: utf-8

"""
    AddSkill

    This is the swagger for LockDownMainHealthy at AddSkill.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: akanksha@addskill.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.meal import Meal  # noqa: E501
from swagger_client.rest import ApiException


class TestMeal(unittest.TestCase):
    """Meal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMeal(self):
        """Test Meal"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.meal.Meal()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
