# coding: utf-8

"""
    AddSkill

    This is the swagger for LockDownMainHealthy at AddSkill.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: akanksha@addskill.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.meal_api import MealApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMealApi(unittest.TestCase):
    """MealApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.meal_api.MealApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_meal(self):
        """Test case for add_meal

        Add meal  # noqa: E501
        """
        pass

    def test_delete_meal(self):
        """Test case for delete_meal

        Delete meal entry  # noqa: E501
        """
        pass

    def test_get_meal_by_meal_id(self):
        """Test case for get_meal_by_meal_id

        Get meal by meal id  # noqa: E501
        """
        pass

    def test_update_meal(self):
        """Test case for update_meal

        Update Meal entry  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
