# coding: utf-8

# flake8: noqa
"""
    AddSkill

    This is the swagger for LockDownMainHealthy at AddSkill.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: akanksha@addskill.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.meal import Meal
from swagger_client.models.user import User
